name: Code-Quality

on:
  workflow_call:
  push:
    branches: [main]
#Check Code_Quality
jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4 

      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps     

      - name: Lint Check
        run: npm run lint

      - name: SAST
        run: npm audit --audit-level=high

      - name: Build App
        run: npm run build



